/* AsmFlow — llhttp ABI adapter.
 *
 * ADR 0006 draws the line: AsmFlow owns the socket, the connection state, the
 * limits, the authentication decision, the dispatch, and the response; llhttp
 * is used only for HTTP/1.1 syntax and body framing. This file is the whole of
 * the boundary between them.
 *
 * It exists for two reasons. `llhttp_settings_t` is a table of twenty-three
 * function pointers whose order is not something assembly should reproduce, and
 * `llhttp_t` has an internal layout that is explicitly not part of llhttp's
 * compatibility promise. Both are described here once, in the language that
 * owns the header.
 *
 * AGENTS.md invariant 2 still applies in full. Nothing here decides anything:
 * every callback is an unconditional forward to an assembly function, and every
 * accessor is a one-line read. No limit, no allowlist, no policy, and no
 * allocation lives on this side.
 *
 * Leniency is not merely left at its default. af_llhttp_request_init clears
 * every lenient flag explicitly and af_llhttp_lenient_flags lets a test read
 * back what the parser is actually running with, so "leniency is disabled"
 * (HARNESS.md M5 DoD 5) is a checked property rather than a comment.
 */

#include <llhttp.h>
#include <stddef.h>
#include <stdint.h>

/* Implemented in src/http/http_parse.asm. Each returns 0 to continue or -1 to
 * stop the parse; the assembly records why it stopped in its own state. */
int af_http_cb_message_begin(void *user);
int af_http_cb_url(void *user, const char *at, size_t length);
int af_http_cb_header_field(void *user, const char *at, size_t length);
int af_http_cb_header_value(void *user, const char *at, size_t length);
int af_http_cb_header_field_complete(void *user);
int af_http_cb_header_value_complete(void *user);
int af_http_cb_headers_complete(void *user);
int af_http_cb_body(void *user, const char *at, size_t length);
int af_http_cb_message_complete(void *user);

/* The trampolines. Written out one by one rather than generated by a macro:
 * `scripts/abi_audit.py` identifies C-defined functions by reading these
 * definitions, and a name that only exists after token pasting is a name the
 * audit cannot see. A security-sensitive boundary (ADR 0006) should be legible
 * to the tools that check it as well as to a reader.
 *
 * Each one does exactly the same thing: hand the user pointer and the span to
 * the assembly, and return whatever it says.
 */
static int af_tramp_message_begin(llhttp_t *parser)
{
    return af_http_cb_message_begin(parser->data);
}

static int af_tramp_url(llhttp_t *parser, const char *at, size_t length)
{
    return af_http_cb_url(parser->data, at, length);
}

static int af_tramp_header_field(llhttp_t *parser, const char *at, size_t length)
{
    return af_http_cb_header_field(parser->data, at, length);
}

static int af_tramp_header_value(llhttp_t *parser, const char *at, size_t length)
{
    return af_http_cb_header_value(parser->data, at, length);
}

static int af_tramp_header_field_complete(llhttp_t *parser)
{
    return af_http_cb_header_field_complete(parser->data);
}

static int af_tramp_header_value_complete(llhttp_t *parser)
{
    return af_http_cb_header_value_complete(parser->data);
}

static int af_tramp_headers_complete(llhttp_t *parser)
{
    return af_http_cb_headers_complete(parser->data);
}

static int af_tramp_body(llhttp_t *parser, const char *at, size_t length)
{
    return af_http_cb_body(parser->data, at, length);
}

static int af_tramp_message_complete(llhttp_t *parser)
{
    return af_http_cb_message_complete(parser->data);
}

/* One settings table for the whole process. llhttp only reads it, and every
 * parser wants the same callbacks, so there is nothing per-connection about it.
 */
static llhttp_settings_t af_http_settings;
static int af_http_settings_ready;

static void af_http_settings_prepare(void)
{
    if (af_http_settings_ready) {
        return;
    }
    llhttp_settings_init(&af_http_settings);
    af_http_settings.on_message_begin = af_tramp_message_begin;
    af_http_settings.on_url = af_tramp_url;
    af_http_settings.on_header_field = af_tramp_header_field;
    af_http_settings.on_header_value = af_tramp_header_value;
    af_http_settings.on_header_field_complete = af_tramp_header_field_complete;
    af_http_settings.on_header_value_complete = af_tramp_header_value_complete;
    af_http_settings.on_headers_complete = af_tramp_headers_complete;
    af_http_settings.on_body = af_tramp_body;
    af_http_settings.on_message_complete = af_tramp_message_complete;
    af_http_settings_ready = 1;
}

/* How much storage a parser needs. include/http.inc reserves a fixed field for
 * it and af_http_server_init asserts this value fits, so a library that grew
 * its state stops the daemon at startup rather than overwriting its neighbour.
 */
size_t af_llhttp_parser_size(void)
{
    return sizeof(llhttp_t);
}

/* Initialise `storage` as a request parser whose callbacks carry `user`. */
void af_llhttp_request_init(void *storage, void *user)
{
    llhttp_t *parser = (llhttp_t *)storage;

    af_http_settings_prepare();
    llhttp_init(parser, HTTP_REQUEST, &af_http_settings);
    parser->data = user;

    /* Off by default in llhttp 9, and set to off here anyway: a default is a
     * property of a version, and this is a property of AsmFlow. */
    llhttp_set_lenient_headers(parser, 0);
    llhttp_set_lenient_chunked_length(parser, 0);
    llhttp_set_lenient_keep_alive(parser, 0);
    llhttp_set_lenient_transfer_encoding(parser, 0);
    llhttp_set_lenient_version(parser, 0);
    llhttp_set_lenient_data_after_close(parser, 0);
    llhttp_set_lenient_optional_lf_after_cr(parser, 0);
    llhttp_set_lenient_optional_cr_before_lf(parser, 0);
    llhttp_set_lenient_optional_crlf_after_chunk(parser, 0);
    llhttp_set_lenient_spaces_after_chunk_size(parser, 0);
}

int af_llhttp_execute(void *storage, const char *data, size_t length)
{
    return (int)llhttp_execute((llhttp_t *)storage, data, length);
}

int af_llhttp_finish(void *storage)
{
    return (int)llhttp_finish((llhttp_t *)storage);
}

int af_llhttp_errno(void *storage)
{
    return (int)llhttp_get_errno((llhttp_t *)storage);
}

const char *af_llhttp_errno_name(int code)
{
    return llhttp_errno_name((llhttp_errno_t)code);
}

/* How many bytes of `data` the parser consumed before it stopped. llhttp
 * reports the position as a pointer into the caller's buffer; the offset is
 * what assembly can use. -1 when no position was recorded. */
int64_t af_llhttp_error_offset(void *storage, const char *data)
{
    const char *pos = llhttp_get_error_pos((llhttp_t *)storage);

    if (pos == NULL || data == NULL) {
        return -1;
    }
    return (int64_t)(pos - data);
}

int af_llhttp_method(void *storage)
{
    return (int)llhttp_get_method((llhttp_t *)storage);
}

int af_llhttp_http_major(void *storage)
{
    return (int)llhttp_get_http_major((llhttp_t *)storage);
}

int af_llhttp_http_minor(void *storage)
{
    return (int)llhttp_get_http_minor((llhttp_t *)storage);
}

int af_llhttp_should_keep_alive(void *storage)
{
    return llhttp_should_keep_alive((llhttp_t *)storage);
}

int af_llhttp_upgrade(void *storage)
{
    return (int)llhttp_get_upgrade((llhttp_t *)storage);
}

/* The lenient bitmask the parser is actually running with. Zero is the only
 * value AsmFlow accepts, and a test asserts it. */
int af_llhttp_lenient_flags(void *storage)
{
    return (int)((llhttp_t *)storage)->lenient_flags;
}

/* The method enumerators, in the order include/http.inc lists them, so a test
 * can assert the two agree rather than trusting a comment (ADR 0007). */
void af_llhttp_method_ordinals(int *out7)
{
    out7[0] = HTTP_DELETE;
    out7[1] = HTTP_GET;
    out7[2] = HTTP_HEAD;
    out7[3] = HTTP_POST;
    out7[4] = HTTP_PUT;
    out7[5] = HTTP_CONNECT;
    out7[6] = HTTP_OPTIONS;
}

/* Likewise for the error codes assembly distinguishes: ok, paused,
 * paused-on-upgrade, and the code a callback's -1 produces. */
void af_llhttp_errno_ordinals(int *out4)
{
    out4[0] = HPE_OK;
    out4[1] = HPE_PAUSED;
    out4[2] = HPE_PAUSED_UPGRADE;
    out4[3] = HPE_USER;
}
